worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /tmp/nginx.pid;

events {
    worker_connections 2048;
}

http {
    include $!{nginx}/conf/mime.types;
    default_type application/octet-stream;
    sendfile on;
    client_max_body_size 35M;

    server {
        listen ${PORT};
        listen [::]:${PORT};
        server_name _;
        root ${NIXPACKS_PHP_ROOT_DIR};
        index index.php;
        charset utf-8;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            include $!{nginx}/conf/fastcgi_params;
            include $!{nginx}/conf/fastcgi.conf;
            fastcgi_buffering off;
            fastcgi_read_timeout 3600s;
            fastcgi_send_timeout 3600s;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}
